### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by Migelo** [Foadsf/Cmathtuts#3]
https://github.com/Foadsf/Cmathtuts/blob/b91ea597a6e6a0d6b99ce07a079bbc60e4b3034e/C_CBLAS/readme.txt#L9

**Comment by Foadsf** [comment]
@Migelo sorry for the very very very late response. I have removed the source files an binaries of the original libraries. Please use netlibs repository here:

http://www.netlib.org/lapack/index.html
